#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.api_key_google_youtube = ""
    args.api_key_pixabay = ""

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.73052c4c.name = "Upgrade from 0.6.4~ynh1"
