#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/source"

# Patch broken dependency
sed -i 's|"v-calendar": "^2.3.0"|"v-calendar": "2.3.0"|' "$install_dir/source/package.json"

#=================================================
# NODEJS BUILD
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir/source"
    echo VUE_APP_PIXABAY_API_KEY="$api_key_pixabay" >> .env
    echo VUE_APP_GOOGLE_API_KEY="$api_key_google_youtube" >> .env

    ynh_exec_as_app npm install
    ynh_exec_as_app npm run build
popd

mv "$install_dir/source/dist" "$install_dir/www"
ynh_safe_rm "$install_dir/source"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
