#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Renamed settings
if [[ -z "${api_key_pixabay:-}" ]]; then
    api_key_pixabay="${pixabay:-}"
    ynh_app_setting_delete --key=pixabay
    ynh_app_setting_set --key="api_key_pixabay" --value="$api_key_pixabay"
fi
if [[ -z "${api_key_google_youtube:-}" ]]; then
    api_key_google_youtube="${googleYoutube:-}"
    ynh_app_setting_delete --key=googleYoutube
    ynh_app_setting_set --key="api_key_google_youtube" --value="$api_key_google_youtube"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source
ynh_setup_source --dest_dir="$install_dir/source" --full_replace

# Patch broken dependency
sed -i 's|"v-calendar": "^2.3.0"|"v-calendar": "2.3.0"|' "$install_dir/source/package.json"

#=================================================
# NODEJS BUILD
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir/source"
    echo VUE_APP_PIXABAY_API_KEY="$api_key_pixabay" >> .env.production
    echo VUE_APP_GOOGLE_API_KEY="$api_key_google_youtube" >> .env.production

    ynh_exec_as_app npm install
    ynh_exec_as_app npm run build
popd

ynh_safe_rm "$install_dir/www"
mv "$install_dir/source/dist" "$install_dir/www"
ynh_safe_rm "$install_dir/source"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
